name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      # This tells Gradle not to output a welcome message when it is started
      GRADLE_OPTS: -Dorg.gradle.internal.launcher.welcomeMessageEnabled=false

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Set up JDK 11
        env:
          SEGMENT_DOWNLOAD_TIMEOUT_MINS: 1
        uses: actions/setup-java@v4.0.0
        with:
          distribution: temurin
          java-version: 11
          java-package: jdk
          cache: gradle

      - name: Report Versions
        run: |
          # Output versions of OS, JDK/JVM, and Gradle
          echo "------------------------------------------------------------"
          echo "Ubuntu Linux"
          echo "------------------------------------------------------------"
          echo
          uname -a
          lsb_release -a
          echo
          echo "------------------------------------------------------------"
          echo "Open JDK"
          echo "------------------------------------------------------------"
          echo
          java -version
          # The following will also download Gradle before actually outputting its version
          ./gradlew --quiet --version

      - name: Check and Test the code
        run: ./gradlew check

      - name: Build the App
        run: ./gradlew build

      - name: Copy built App
        run: |
          mkdir --parents artifacts/app
          cp build/libs/cryptarithmetic-solver-*-all.jar artifacts/app/

      - name: Upload JAR
        uses: actions/upload-artifact@v4.2.0
        with:
          name: Cryptarithmetic-Solver-app
          path: artifacts/app/
          compression-level: 0

      - name: Collect Reports
        if: always()
        run: |
          mkdir --parents artifacts/reports
          if [[ -d "build/reports" ]]; then
              cp --preserve=mode,ownership,timestamps --recursive "build/reports/"* "artifacts/reports/"
          fi

      - name: Upload Reports
        if: always()
        uses: actions/upload-artifact@v4.2.0
        with:
          name: Cryptarithmetic-Solver-reports
          path: artifacts/reports/
